server.port=8081
server.servlet.session.cookie.name=HALO_SESSION

## Hydra
#oauth2.public_url=http://127.0.0.1:4444
## Keycloak
oauth2.public_url=http://localhost:7070/realms/master

obp.base_url=http://localhost:8080
endpoint.path.prefix=${obp.base_url}/open-banking/v3.1

# MTLS related, config keystore and truststore
## keystore and truststore files can be local files or web resources, as example:
#mtls.keyStore.path=file:///Users/apple/dev/code/OBP-API-PARENT/obp-api/src/test/resources/cert/client2.jks
#mtls.keyStore.path=classpath:cert/user2.jks
###mtls.keyStore.path=http://<some domain>/user.old.jks
###mtls.keyStore.password=123456
#mtls.keyStore.password=waiJaeP7sake
#mtls.keyStore.alias=1
#mtls.trustStore.path=classpath:cert/ofpilot.jks
###mtls.trustStore.path=http://<some domain>/ofpilot.jks
#mtls.trustStore.password=changeit


mtls.keyStore.path=file:///Users/zhanghongwei/Documents/GitHub-Tower/OBP-Hola/src/main/resources/cert/hola_san_dns_ip.jks
mtls.keyStore.password=123456
mtls.keyStore.alias=1
mtls.trustStore.path=file:///Users/zhanghongwei/Documents/GitHub-Tower/OBP-Hola/src/main/resources/cert/new_server.trust.jks
mtls.trustStore.password=123456

## Keycloak-client-SingedJwt
oauth2.client_id=jwt-client
oauth2.jwk_private_key={"crv": "P-256","d": "Vu5djR1CMwsbla4lvMpdFH21NSiCEV7LDYm756tX7b8","kid": "fARclOscOpTdbKi1ik7zOGbCRfscJE-ad1dg88ZGaqA","kty": "EC","x": "8r5FfzcQxVwlXsSrzyLP5mMqdCgfaQjWPuKexPV2FN8","y": "NE_hSiV3n1-qpHy4C_gCI-XnoLsYWWjsIPguN5b6OMs"}
## Keycloak-secret
#oauth2.client_id=open-bank-project
#oauth2.client_secret=ygVDHw7dGkd508WmmZhMga7cCaZ5DDHb

oauth2.redirect_uri=http://localhost:8081/main2.html
oauth2.jws_alg=ES256
oauth2.client_scope=ReadAccountsBasic,\
ReadAccountsDetail,\
ReadBalances,\
ReadTransactionsBasic,\
ReadTransactionsDebits,\
ReadTransactionsDetail,\
ReadAccountsBerlinGroup,\
ReadBalancesBerlinGroup,\
ReadTransactionsBerlinGroup


### Force the feature of signing/verifying requests on a certain standard
#force_jws=BGv1.3
force_jws=None
#display_standards=UKOpenBanking,BerlinGroup
display_standards=BerlinGroup

#button.background_color=#B50938
#button.hover.background_color=#8E072C

logging.level.root=INFO

### Show internal server errors to the end user
show_unhandled_errors=true

#logo.bank.enabled=true
logo.bank.url=https://static.openbankproject.com/finca/img/finca-logo.png